#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
#ifndef WUNDERKINDKIT_SWIFT_H
#define WUNDERKINDKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WunderkindKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

typedef SWIFT_ENUM(NSInteger, AccountType, open) {
  AccountTypeBusiness = 0,
  AccountTypeLeisure = 1,
};


@class NSString;
@class RentalDetails;
@class CarRentalRequest;
@class RentalAccount;

SWIFT_CLASS("_TtC13WunderkindKit18CarRentalAddToCart")
@interface CarRentalAddToCart : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull selectedOption;
@property (nonatomic, readonly) BOOL isRentalOneWay;
@property (nonatomic, readonly, strong) RentalDetails * _Nonnull details;
@property (nonatomic, readonly, strong) CarRentalRequest * _Nonnull request;
@property (nonatomic, readonly, strong) RentalAccount * _Nonnull account;
- (nonnull instancetype)initWithSelectedOption:(NSString * _Nonnull)selectedOption isRentalOneWay:(BOOL)isRentalOneWay details:(RentalDetails * _Nonnull)details request:(CarRentalRequest * _Nonnull)request account:(RentalAccount * _Nonnull)account OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;

SWIFT_UNAVAILABLE
@interface CarRentalAddToCart (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithSelectedOption:(NSString * _Nonnull)selectedOption isRentalOneWay:(NSNumber * _Nullable)isRentalOneWay rentalDetails:(RentalDetails * _Nullable)rentalDetails request:(CarRentalRequest * _Nullable)request account:(RentalAccount * _Nullable)account;
@end



SWIFT_CLASS("_TtC13WunderkindKit17CarRentalProgress")
@interface CarRentalProgress : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull options;
@property (nonatomic, readonly) BOOL isRentalOneWay;
@property (nonatomic, readonly, strong) RentalDetails * _Nonnull details;
@property (nonatomic, readonly, strong) CarRentalRequest * _Nonnull request;
@property (nonatomic, readonly, strong) RentalAccount * _Nonnull account;
- (nonnull instancetype)initWithOptions:(NSArray<NSString *> * _Nonnull)options isRentalOneWay:(BOOL)isRentalOneWay details:(RentalDetails * _Nonnull)details request:(CarRentalRequest * _Nonnull)request account:(RentalAccount * _Nonnull)account OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface CarRentalProgress (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithOptions:(NSArray<NSString *> * _Nonnull)options isRentalOneWay:(NSNumber * _Nullable)isRentalOneWay rentalDetails:(RentalDetails * _Nullable)rentalDetails request:(CarRentalRequest * _Nullable)request account:(RentalAccount * _Nullable)account;
@end


@class RentalLocation;

SWIFT_CLASS("_TtC13WunderkindKit16CarRentalRequest")
@interface CarRentalRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable carCode;
@property (nonatomic, readonly, strong) RentalLocation * _Nonnull startLocation;
@property (nonatomic, readonly, strong) RentalLocation * _Nullable dropOffLocation;
@property (nonatomic, readonly) NSTimeInterval startTimestamp;
@property (nonatomic, readonly) NSTimeInterval endTimestamp;
- (nonnull instancetype)initWithCarCode:(NSString * _Nullable)carCode startLocation:(RentalLocation * _Nonnull)startLocation dropOffLocation:(RentalLocation * _Nullable)dropOffLocation startTimestamp:(NSTimeInterval)startTimestamp endTimestamp:(NSTimeInterval)endTimestamp OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface CarRentalRequest (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithCarCode:(NSString * _Nullable)carCode startRentalLocation:(RentalLocation * _Nullable)startRentalLocation dropOffLocation:(RentalLocation * _Nullable)dropOffLocation startTimestamp:(NSTimeInterval)startTimestamp endTimestamp:(NSTimeInterval)endTimestamp;
@end


typedef SWIFT_ENUM(NSInteger, Currency, open) {
  CurrencyUSD = 0,
  CurrencyKRW = 1,
  CurrencyAED = 2,
  CurrencyLTL = 3,
  CurrencyARS = 4,
  CurrencyMAD = 5,
  CurrencyAUD = 6,
  CurrencyMXN = 7,
  CurrencyBGN = 8,
  CurrencyMYR = 9,
  CurrencyBOB = 10,
  CurrencyNOK = 11,
  CurrencyBRL = 12,
  CurrencyNZD = 13,
  CurrencyCAD = 14,
  CurrencyPEN = 15,
  CurrencyCHF = 16,
  CurrencyPHP = 17,
  CurrencyCLP = 18,
  CurrencyPKR = 19,
  CurrencyCNY = 20,
  CurrencyPLN = 21,
  CurrencyCOP = 22,
  CurrencyRON = 23,
  CurrencyCZK = 24,
  CurrencyRSD = 25,
  CurrencyDKK = 26,
  CurrencyRUB = 27,
  CurrencyEGP = 28,
  CurrencySAR = 29,
  CurrencyEUR = 30,
  CurrencySEK = 31,
  CurrencyGBP = 32,
  CurrencySGD = 33,
  CurrencyHKD = 34,
  CurrencyTHB = 35,
  CurrencyHRK = 36,
  CurrencyTRY = 37,
  CurrencyHUF = 38,
  CurrencyTWD = 39,
  CurrencyIDR = 40,
  CurrencyUAH = 41,
  CurrencyILS = 42,
  CurrencyVEF = 43,
  CurrencyINR = 44,
  CurrencyVND = 45,
  CurrencyJPY = 46,
  CurrencyZAR = 47,
};

@class Order;

SWIFT_CLASS("_TtC13WunderkindKit11CustomOrder")
@interface CustomOrder : NSObject
@property (nonatomic, readonly) int64_t websiteId;
@property (nonatomic, readonly, strong) Order * _Nonnull order;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface CustomOrder (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithWebsiteId:(int64_t)websiteId order:(Order * _Nullable)order;
@end



SWIFT_CLASS("_TtC13WunderkindKit8Customer")
@interface Customer : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull email;
@property (nonatomic, readonly, copy) NSString * _Nullable phone;
@property (nonatomic, readonly) BOOL isHashed;
- (nonnull instancetype)initWithEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone isHashed:(BOOL)isHashed OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithEmail:(NSString * _Nonnull)email isHashed:(BOOL)isHashed OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithEmail:(NSString * _Nonnull)email OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





@class HotelRentalRequest;

SWIFT_CLASS("_TtC13WunderkindKit20HotelRentalAddToCart")
@interface HotelRentalAddToCart : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull selectedOption;
@property (nonatomic, readonly, strong) RentalDetails * _Nonnull details;
@property (nonatomic, readonly, strong) HotelRentalRequest * _Nonnull request;
@property (nonatomic, readonly, strong) RentalAccount * _Nonnull account;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface HotelRentalAddToCart (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithSelectedOption:(NSString * _Nonnull)selectedOption roomsCount:(NSInteger)roomsCount rentalDetails:(RentalDetails * _Nullable)rentalDetails request:(HotelRentalRequest * _Nullable)request account:(RentalAccount * _Nullable)account;
@end



SWIFT_CLASS("_TtC13WunderkindKit19HotelRentalProgress")
@interface HotelRentalProgress : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull options;
@property (nonatomic, readonly, strong) RentalDetails * _Nonnull details;
@property (nonatomic, readonly, strong) HotelRentalRequest * _Nonnull request;
@property (nonatomic, readonly, strong) RentalAccount * _Nonnull account;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface HotelRentalProgress (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithOptions:(NSArray<NSString *> * _Nonnull)options roomsCount:(NSInteger)roomsCount rentalDetails:(RentalDetails * _Nullable)rentalDetails request:(HotelRentalRequest * _Nullable)request account:(RentalAccount * _Nullable)account;
@end



SWIFT_CLASS("_TtC13WunderkindKit18HotelRentalRequest")
@interface HotelRentalRequest : NSObject
@property (nonatomic, readonly, strong) RentalLocation * _Nonnull rentalLocation;
@property (nonatomic, readonly) NSTimeInterval startTimestamp;
@property (nonatomic, readonly) NSTimeInterval endTimestamp;
- (nonnull instancetype)initWithRentalLocation:(RentalLocation * _Nonnull)rentalLocation startTimestamp:(NSTimeInterval)startTimestamp endTimestamp:(NSTimeInterval)endTimestamp OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface HotelRentalRequest (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithStartRentalLocation:(RentalLocation * _Nullable)startRentalLocation startTimestamp:(NSTimeInterval)startTimestamp endTimestamp:(NSTimeInterval)endTimestamp;
@end



SWIFT_CLASS("_TtC13WunderkindKit7Invoice")
@interface Invoice : NSObject
@property (nonatomic, readonly) NSDecimal amount;
@property (nonatomic, readonly) NSDecimal tax;
@property (nonatomic, readonly) NSDecimal shipping;
@property (nonatomic, readonly) enum Currency currency;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDecimalNumber;

SWIFT_UNAVAILABLE
@interface Invoice (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithAmount:(NSDecimalNumber * _Nullable)amount tax:(NSDecimalNumber * _Nullable)tax totalDiscount:(NSDecimalNumber * _Nullable)totalDiscount shipping:(NSDecimalNumber * _Nullable)shipping currency:(enum Currency)currency;
@end


typedef SWIFT_ENUM(NSInteger, LogLevel, open) {
  LogLevelNone = 0,
  LogLevelDebug = 1,
  LogLevelInfo = 2,
};

typedef SWIFT_ENUM(NSInteger, LoginMethod, open) {
  LoginMethodEmail = 0,
  LoginMethodTwitter = 1,
  LoginMethodFacebook = 2,
  LoginMethodGoogle = 3,
  LoginMethodApple = 4,
};

@class Product;

SWIFT_CLASS("_TtC13WunderkindKit5Order")
@interface Order : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull orderId;
@property (nonatomic, readonly, strong) Invoice * _Nonnull invoice;
@property (nonatomic, readonly, copy) NSString * _Nullable paymentMethod;
@property (nonatomic, readonly, copy) NSArray<Product *> * _Nonnull products;
@property (nonatomic, readonly, strong) Customer * _Nonnull customer;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable coupons;
@property (nonatomic, readonly, copy) NSString * _Nonnull goal;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface Order (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithOrderId:(NSString * _Nonnull)orderId invoice:(Invoice * _Nullable)invoice paymentMethod:(NSString * _Nullable)paymentMethod products:(NSArray<Product *> * _Nullable)products customer:(Customer * _Nullable)customer coupons:(NSArray<NSString *> * _Nullable)coupons goal:(NSString * _Nonnull)goal;
@end



SWIFT_CLASS("_TtC13WunderkindKit7Product")
@interface Product : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull productId;
@property (nonatomic, readonly, copy) NSString * _Nonnull skuId;
@property (nonatomic, readonly) NSDecimal price;
@property (nonatomic, readonly) int64_t quantity;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface Product (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithProductId:(NSString * _Nonnull)productId skuId:(NSString * _Nonnull)skuId quantity:(int64_t)quantity price:(NSDecimalNumber * _Nullable)price;
@end


@class NSURL;

SWIFT_CLASS("_TtC13WunderkindKit15ProductCategory")
@interface ProductCategory : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSURL * _Nonnull url;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull itemIds;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface ProductCategory (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title url:(NSURL * _Nullable)url itemIds:(NSArray<NSString *> * _Nullable)itemIds;
@end



SWIFT_CLASS("_TtC13WunderkindKit13RentalAccount")
@interface RentalAccount : NSObject
@property (nonatomic, readonly) enum AccountType accountType;
@property (nonatomic, readonly, copy) NSString * _Nullable affiliateNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable countryOfResidence;
@property (nonatomic, readonly) NSDecimal age;
- (nonnull instancetype)initWithAccountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nullable)affiliateNumber countryOfResidence:(NSString * _Nullable)countryOfResidence age:(NSDecimal)age OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface RentalAccount (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithAccountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nullable)affiliateNumber countryOfResidence:(NSString * _Nullable)countryOfResidence userAge:(NSDecimalNumber * _Nullable)userAge;
@end



SWIFT_CLASS("_TtC13WunderkindKit13RentalDetails")
@interface RentalDetails : NSObject
@property (nonatomic, readonly) BOOL ancillaryItems;
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSURL * _Nonnull url;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface RentalDetails (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithAncillaryItems:(NSNumber * _Nullable)ancillaryItems stepNumber:(NSInteger)stepNumber travelersCount:(NSInteger)travelersCount title:(NSString * _Nonnull)title url:(NSURL * _Nullable)url;
@end



SWIFT_CLASS("_TtC13WunderkindKit14RentalLocation")
@interface RentalLocation : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title code:(NSString * _Nonnull)code OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC13WunderkindKit11RentalOrder")
@interface RentalOrder : NSObject
@property (nonatomic, readonly) enum AccountType accountType;
@property (nonatomic, readonly, copy) NSString * _Nullable affiliateNumber;
@property (nonatomic, readonly, strong) Order * _Nonnull order;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface RentalOrder (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithAccountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nullable)affiliateNumber order:(Order * _Nullable)order;
@end


typedef SWIFT_ENUM(NSInteger, ScreenType, open) {
  ScreenTypeHome = 0,
  ScreenTypeProduct = 1,
  ScreenTypeCategory = 2,
  ScreenTypeSearch = 3,
  ScreenTypeCart = 4,
  ScreenTypeArticle = 5,
  ScreenTypeGallery = 6,
  ScreenTypeCheckout = 7,
};







SWIFT_CLASS("_TtC13WunderkindKit10Wunderkind")
@interface Wunderkind : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Wunderkind * _Nonnull shared;)
+ (Wunderkind * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) enum LogLevel logLevel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@interface Wunderkind (SWIFT_EXTENSION(WunderkindKit))
- (void)initializeWithWebsiteId:(int64_t)websiteId isDebugMode:(BOOL)isDebugMode;
- (void)initializeWithWebsiteId:(int64_t)websiteId isDebugMode:(BOOL)isDebugMode isMultipleWebsiteIdMode:(BOOL)isMultipleWebsiteIdMode;
@property (nonatomic) BOOL isContextInfoTrackingEnabled;
@end



SWIFT_UNAVAILABLE
@interface Wunderkind (SWIFT_EXTENSION(WunderkindKit))
- (void)trackScreenViewWithUrl:(NSURL * _Nullable)url type:(enum ScreenType)type;
- (void)trackViewCategoryWithCategory:(ProductCategory * _Nullable)category;
- (void)trackViewSearchWithCategory:(ProductCategory * _Nullable)category;
- (void)trackCarRentalProgressWithProgress:(CarRentalProgress * _Nullable)progress;
- (void)trackCarRentalAddToCartWithRental:(CarRentalAddToCart * _Nullable)rental;
- (void)trackHotelRentalAddToCartWithRental:(HotelRentalAddToCart * _Nullable)rental;
- (void)trackHotelRentalProgressWithProgress:(HotelRentalProgress * _Nullable)progress;
- (void)trackPurchaseWithOrder:(Order * _Nullable)order;
- (void)trackRentalPurchaseWithOrder:(RentalOrder * _Nullable)order;
@end

@class NSData;
@class UNNotification;

@interface Wunderkind (SWIFT_EXTENSION(WunderkindKit))
- (void)trackViewItemWithItemId:(NSString * _Nonnull)itemId groupId:(NSString * _Nonnull)groupId;
- (void)trackAppPushTokenSetWithDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)trackAppPushOptIn;
- (void)trackAppPushOptOut;
- (void)trackAppPushOpenedWithAppPush:(UNNotification * _Nonnull)appPush;
- (void)trackAppPushDeliveredWithAppPush:(UNNotification * _Nonnull)appPush;
- (void)trackExistingLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone SWIFT_DEPRECATED_MSG("", "trackLoggedInEmail:phone:");
- (void)trackExistingLoggedInEmail:(NSString * _Nonnull)email SWIFT_DEPRECATED_MSG("", "trackLoggedInEmail:");
- (void)trackExistingAffiliateLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber SWIFT_DEPRECATED_MSG("", "trackAffiliateLoggedInEmail:phone:accountType:affiliateNumber:");
- (void)trackHashedExistingLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone SWIFT_DEPRECATED_MSG("", "trackHashedLoggedInEmail:phone:");
- (void)trackHashedExistingLoggedInEmail:(NSString * _Nonnull)email SWIFT_DEPRECATED_MSG("", "trackHashedLoggedInEmail:");
- (void)trackHashedExistingAffiliateLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber SWIFT_DEPRECATED_MSG("", "trackHashedAffiliateLoggedInEmail:phone:accountType:affiliateNumber:");
- (void)trackAddToCartWithItemId:(NSString * _Nonnull)itemId;
- (void)trackEmptyCart;
- (void)trackLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method phone:(NSString * _Nonnull)phone SWIFT_DEPRECATED_MSG("", "trackLoggedInEmail:phone:");
- (void)trackLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone;
- (void)trackLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method SWIFT_DEPRECATED_MSG("", "trackLoggedInEmail:");
- (void)trackLoggedInEmail:(NSString * _Nonnull)email;
- (void)trackAffiliateLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber SWIFT_DEPRECATED_MSG("", "trackAffiliateLoggedInEmail:phone:accountType:affiliateNumber:");
- (void)trackAffiliateLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber;
- (void)trackHashedLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method phone:(NSString * _Nonnull)phone SWIFT_DEPRECATED_MSG("", "trackHashedLoggedInEmail:phone:");
- (void)trackHashedLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone;
- (void)trackHashedLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method SWIFT_DEPRECATED_MSG("", "trackHashedLoggedInEmail:");
- (void)trackHashedLoggedInEmail:(NSString * _Nonnull)email;
- (void)trackHashedAffiliateLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber SWIFT_DEPRECATED_MSG("", "trackHashedAffiliateLoggedInEmail:phone:accountType:affiliateNumber:");
- (void)trackHashedAffiliateLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber;
- (void)trackLoggedOut;
- (void)trackEndVisit;
- (NSString * _Nonnull)getDeviceID SWIFT_WARN_UNUSED_RESULT;
- (void)trackCustomWithEventName:(NSString * _Nonnull)eventName extraData:(NSDictionary<NSString *, NSString *> * _Nonnull)extraData;
- (void)trackSelectSKUWithGroupId:(NSString * _Nonnull)groupId feedId:(NSString * _Nonnull)feedId;
- (void)trackMultiplePurchasesWithOrders:(NSArray<CustomOrder *> * _Nonnull)orders;
- (void)trackTextOptInPhoneNumber:(NSString * _Nonnull)phoneNumber languageCode:(NSString * _Nullable)languageCode;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
#ifndef WUNDERKINDKIT_SWIFT_H
#define WUNDERKINDKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WunderkindKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

typedef SWIFT_ENUM(NSInteger, AccountType, open) {
  AccountTypeBusiness = 0,
  AccountTypeLeisure = 1,
};


@class NSString;
@class RentalDetails;
@class CarRentalRequest;
@class RentalAccount;

SWIFT_CLASS("_TtC13WunderkindKit18CarRentalAddToCart")
@interface CarRentalAddToCart : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull selectedOption;
@property (nonatomic, readonly) BOOL isRentalOneWay;
@property (nonatomic, readonly, strong) RentalDetails * _Nonnull details;
@property (nonatomic, readonly, strong) CarRentalRequest * _Nonnull request;
@property (nonatomic, readonly, strong) RentalAccount * _Nonnull account;
- (nonnull instancetype)initWithSelectedOption:(NSString * _Nonnull)selectedOption isRentalOneWay:(BOOL)isRentalOneWay details:(RentalDetails * _Nonnull)details request:(CarRentalRequest * _Nonnull)request account:(RentalAccount * _Nonnull)account OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;

SWIFT_UNAVAILABLE
@interface CarRentalAddToCart (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithSelectedOption:(NSString * _Nonnull)selectedOption isRentalOneWay:(NSNumber * _Nullable)isRentalOneWay rentalDetails:(RentalDetails * _Nullable)rentalDetails request:(CarRentalRequest * _Nullable)request account:(RentalAccount * _Nullable)account;
@end



SWIFT_CLASS("_TtC13WunderkindKit17CarRentalProgress")
@interface CarRentalProgress : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull options;
@property (nonatomic, readonly) BOOL isRentalOneWay;
@property (nonatomic, readonly, strong) RentalDetails * _Nonnull details;
@property (nonatomic, readonly, strong) CarRentalRequest * _Nonnull request;
@property (nonatomic, readonly, strong) RentalAccount * _Nonnull account;
- (nonnull instancetype)initWithOptions:(NSArray<NSString *> * _Nonnull)options isRentalOneWay:(BOOL)isRentalOneWay details:(RentalDetails * _Nonnull)details request:(CarRentalRequest * _Nonnull)request account:(RentalAccount * _Nonnull)account OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface CarRentalProgress (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithOptions:(NSArray<NSString *> * _Nonnull)options isRentalOneWay:(NSNumber * _Nullable)isRentalOneWay rentalDetails:(RentalDetails * _Nullable)rentalDetails request:(CarRentalRequest * _Nullable)request account:(RentalAccount * _Nullable)account;
@end


@class RentalLocation;

SWIFT_CLASS("_TtC13WunderkindKit16CarRentalRequest")
@interface CarRentalRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable carCode;
@property (nonatomic, readonly, strong) RentalLocation * _Nonnull startLocation;
@property (nonatomic, readonly, strong) RentalLocation * _Nullable dropOffLocation;
@property (nonatomic, readonly) NSTimeInterval startTimestamp;
@property (nonatomic, readonly) NSTimeInterval endTimestamp;
- (nonnull instancetype)initWithCarCode:(NSString * _Nullable)carCode startLocation:(RentalLocation * _Nonnull)startLocation dropOffLocation:(RentalLocation * _Nullable)dropOffLocation startTimestamp:(NSTimeInterval)startTimestamp endTimestamp:(NSTimeInterval)endTimestamp OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface CarRentalRequest (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithCarCode:(NSString * _Nullable)carCode startRentalLocation:(RentalLocation * _Nullable)startRentalLocation dropOffLocation:(RentalLocation * _Nullable)dropOffLocation startTimestamp:(NSTimeInterval)startTimestamp endTimestamp:(NSTimeInterval)endTimestamp;
@end


typedef SWIFT_ENUM(NSInteger, Currency, open) {
  CurrencyUSD = 0,
  CurrencyKRW = 1,
  CurrencyAED = 2,
  CurrencyLTL = 3,
  CurrencyARS = 4,
  CurrencyMAD = 5,
  CurrencyAUD = 6,
  CurrencyMXN = 7,
  CurrencyBGN = 8,
  CurrencyMYR = 9,
  CurrencyBOB = 10,
  CurrencyNOK = 11,
  CurrencyBRL = 12,
  CurrencyNZD = 13,
  CurrencyCAD = 14,
  CurrencyPEN = 15,
  CurrencyCHF = 16,
  CurrencyPHP = 17,
  CurrencyCLP = 18,
  CurrencyPKR = 19,
  CurrencyCNY = 20,
  CurrencyPLN = 21,
  CurrencyCOP = 22,
  CurrencyRON = 23,
  CurrencyCZK = 24,
  CurrencyRSD = 25,
  CurrencyDKK = 26,
  CurrencyRUB = 27,
  CurrencyEGP = 28,
  CurrencySAR = 29,
  CurrencyEUR = 30,
  CurrencySEK = 31,
  CurrencyGBP = 32,
  CurrencySGD = 33,
  CurrencyHKD = 34,
  CurrencyTHB = 35,
  CurrencyHRK = 36,
  CurrencyTRY = 37,
  CurrencyHUF = 38,
  CurrencyTWD = 39,
  CurrencyIDR = 40,
  CurrencyUAH = 41,
  CurrencyILS = 42,
  CurrencyVEF = 43,
  CurrencyINR = 44,
  CurrencyVND = 45,
  CurrencyJPY = 46,
  CurrencyZAR = 47,
};

@class Order;

SWIFT_CLASS("_TtC13WunderkindKit11CustomOrder")
@interface CustomOrder : NSObject
@property (nonatomic, readonly) int64_t websiteId;
@property (nonatomic, readonly, strong) Order * _Nonnull order;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface CustomOrder (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithWebsiteId:(int64_t)websiteId order:(Order * _Nullable)order;
@end



SWIFT_CLASS("_TtC13WunderkindKit8Customer")
@interface Customer : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull email;
@property (nonatomic, readonly, copy) NSString * _Nullable phone;
@property (nonatomic, readonly) BOOL isHashed;
- (nonnull instancetype)initWithEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone isHashed:(BOOL)isHashed OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithEmail:(NSString * _Nonnull)email isHashed:(BOOL)isHashed OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithEmail:(NSString * _Nonnull)email OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





@class HotelRentalRequest;

SWIFT_CLASS("_TtC13WunderkindKit20HotelRentalAddToCart")
@interface HotelRentalAddToCart : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull selectedOption;
@property (nonatomic, readonly, strong) RentalDetails * _Nonnull details;
@property (nonatomic, readonly, strong) HotelRentalRequest * _Nonnull request;
@property (nonatomic, readonly, strong) RentalAccount * _Nonnull account;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface HotelRentalAddToCart (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithSelectedOption:(NSString * _Nonnull)selectedOption roomsCount:(NSInteger)roomsCount rentalDetails:(RentalDetails * _Nullable)rentalDetails request:(HotelRentalRequest * _Nullable)request account:(RentalAccount * _Nullable)account;
@end



SWIFT_CLASS("_TtC13WunderkindKit19HotelRentalProgress")
@interface HotelRentalProgress : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull options;
@property (nonatomic, readonly, strong) RentalDetails * _Nonnull details;
@property (nonatomic, readonly, strong) HotelRentalRequest * _Nonnull request;
@property (nonatomic, readonly, strong) RentalAccount * _Nonnull account;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface HotelRentalProgress (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithOptions:(NSArray<NSString *> * _Nonnull)options roomsCount:(NSInteger)roomsCount rentalDetails:(RentalDetails * _Nullable)rentalDetails request:(HotelRentalRequest * _Nullable)request account:(RentalAccount * _Nullable)account;
@end



SWIFT_CLASS("_TtC13WunderkindKit18HotelRentalRequest")
@interface HotelRentalRequest : NSObject
@property (nonatomic, readonly, strong) RentalLocation * _Nonnull rentalLocation;
@property (nonatomic, readonly) NSTimeInterval startTimestamp;
@property (nonatomic, readonly) NSTimeInterval endTimestamp;
- (nonnull instancetype)initWithRentalLocation:(RentalLocation * _Nonnull)rentalLocation startTimestamp:(NSTimeInterval)startTimestamp endTimestamp:(NSTimeInterval)endTimestamp OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface HotelRentalRequest (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithStartRentalLocation:(RentalLocation * _Nullable)startRentalLocation startTimestamp:(NSTimeInterval)startTimestamp endTimestamp:(NSTimeInterval)endTimestamp;
@end



SWIFT_CLASS("_TtC13WunderkindKit7Invoice")
@interface Invoice : NSObject
@property (nonatomic, readonly) NSDecimal amount;
@property (nonatomic, readonly) NSDecimal tax;
@property (nonatomic, readonly) NSDecimal shipping;
@property (nonatomic, readonly) enum Currency currency;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDecimalNumber;

SWIFT_UNAVAILABLE
@interface Invoice (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithAmount:(NSDecimalNumber * _Nullable)amount tax:(NSDecimalNumber * _Nullable)tax totalDiscount:(NSDecimalNumber * _Nullable)totalDiscount shipping:(NSDecimalNumber * _Nullable)shipping currency:(enum Currency)currency;
@end


typedef SWIFT_ENUM(NSInteger, LogLevel, open) {
  LogLevelNone = 0,
  LogLevelDebug = 1,
  LogLevelInfo = 2,
};

typedef SWIFT_ENUM(NSInteger, LoginMethod, open) {
  LoginMethodEmail = 0,
  LoginMethodTwitter = 1,
  LoginMethodFacebook = 2,
  LoginMethodGoogle = 3,
  LoginMethodApple = 4,
};

@class Product;

SWIFT_CLASS("_TtC13WunderkindKit5Order")
@interface Order : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull orderId;
@property (nonatomic, readonly, strong) Invoice * _Nonnull invoice;
@property (nonatomic, readonly, copy) NSString * _Nullable paymentMethod;
@property (nonatomic, readonly, copy) NSArray<Product *> * _Nonnull products;
@property (nonatomic, readonly, strong) Customer * _Nonnull customer;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable coupons;
@property (nonatomic, readonly, copy) NSString * _Nonnull goal;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface Order (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithOrderId:(NSString * _Nonnull)orderId invoice:(Invoice * _Nullable)invoice paymentMethod:(NSString * _Nullable)paymentMethod products:(NSArray<Product *> * _Nullable)products customer:(Customer * _Nullable)customer coupons:(NSArray<NSString *> * _Nullable)coupons goal:(NSString * _Nonnull)goal;
@end



SWIFT_CLASS("_TtC13WunderkindKit7Product")
@interface Product : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull productId;
@property (nonatomic, readonly, copy) NSString * _Nonnull skuId;
@property (nonatomic, readonly) NSDecimal price;
@property (nonatomic, readonly) int64_t quantity;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface Product (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithProductId:(NSString * _Nonnull)productId skuId:(NSString * _Nonnull)skuId quantity:(int64_t)quantity price:(NSDecimalNumber * _Nullable)price;
@end


@class NSURL;

SWIFT_CLASS("_TtC13WunderkindKit15ProductCategory")
@interface ProductCategory : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSURL * _Nonnull url;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull itemIds;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface ProductCategory (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title url:(NSURL * _Nullable)url itemIds:(NSArray<NSString *> * _Nullable)itemIds;
@end



SWIFT_CLASS("_TtC13WunderkindKit13RentalAccount")
@interface RentalAccount : NSObject
@property (nonatomic, readonly) enum AccountType accountType;
@property (nonatomic, readonly, copy) NSString * _Nullable affiliateNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable countryOfResidence;
@property (nonatomic, readonly) NSDecimal age;
- (nonnull instancetype)initWithAccountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nullable)affiliateNumber countryOfResidence:(NSString * _Nullable)countryOfResidence age:(NSDecimal)age OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface RentalAccount (SWIFT_EXTENSION(WunderkindKit))
- (nonnull instancetype)initWithAccountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nullable)affiliateNumber countryOfResidence:(NSString * _Nullable)countryOfResidence userAge:(NSDecimalNumber * _Nullable)userAge;
@end



SWIFT_CLASS("_TtC13WunderkindKit13RentalDetails")
@interface RentalDetails : NSObject
@property (nonatomic, readonly) BOOL ancillaryItems;
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSURL * _Nonnull url;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface RentalDetails (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithAncillaryItems:(NSNumber * _Nullable)ancillaryItems stepNumber:(NSInteger)stepNumber travelersCount:(NSInteger)travelersCount title:(NSString * _Nonnull)title url:(NSURL * _Nullable)url;
@end



SWIFT_CLASS("_TtC13WunderkindKit14RentalLocation")
@interface RentalLocation : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title code:(NSString * _Nonnull)code OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC13WunderkindKit11RentalOrder")
@interface RentalOrder : NSObject
@property (nonatomic, readonly) enum AccountType accountType;
@property (nonatomic, readonly, copy) NSString * _Nullable affiliateNumber;
@property (nonatomic, readonly, strong) Order * _Nonnull order;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_UNAVAILABLE
@interface RentalOrder (SWIFT_EXTENSION(WunderkindKit))
- (nullable instancetype)initWithAccountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nullable)affiliateNumber order:(Order * _Nullable)order;
@end


typedef SWIFT_ENUM(NSInteger, ScreenType, open) {
  ScreenTypeHome = 0,
  ScreenTypeProduct = 1,
  ScreenTypeCategory = 2,
  ScreenTypeSearch = 3,
  ScreenTypeCart = 4,
  ScreenTypeArticle = 5,
  ScreenTypeGallery = 6,
  ScreenTypeCheckout = 7,
};







SWIFT_CLASS("_TtC13WunderkindKit10Wunderkind")
@interface Wunderkind : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Wunderkind * _Nonnull shared;)
+ (Wunderkind * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) enum LogLevel logLevel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@interface Wunderkind (SWIFT_EXTENSION(WunderkindKit))
- (void)initializeWithWebsiteId:(int64_t)websiteId isDebugMode:(BOOL)isDebugMode;
- (void)initializeWithWebsiteId:(int64_t)websiteId isDebugMode:(BOOL)isDebugMode isMultipleWebsiteIdMode:(BOOL)isMultipleWebsiteIdMode;
@property (nonatomic) BOOL isContextInfoTrackingEnabled;
@end



SWIFT_UNAVAILABLE
@interface Wunderkind (SWIFT_EXTENSION(WunderkindKit))
- (void)trackScreenViewWithUrl:(NSURL * _Nullable)url type:(enum ScreenType)type;
- (void)trackViewCategoryWithCategory:(ProductCategory * _Nullable)category;
- (void)trackViewSearchWithCategory:(ProductCategory * _Nullable)category;
- (void)trackCarRentalProgressWithProgress:(CarRentalProgress * _Nullable)progress;
- (void)trackCarRentalAddToCartWithRental:(CarRentalAddToCart * _Nullable)rental;
- (void)trackHotelRentalAddToCartWithRental:(HotelRentalAddToCart * _Nullable)rental;
- (void)trackHotelRentalProgressWithProgress:(HotelRentalProgress * _Nullable)progress;
- (void)trackPurchaseWithOrder:(Order * _Nullable)order;
- (void)trackRentalPurchaseWithOrder:(RentalOrder * _Nullable)order;
@end

@class NSData;
@class UNNotification;

@interface Wunderkind (SWIFT_EXTENSION(WunderkindKit))
- (void)trackViewItemWithItemId:(NSString * _Nonnull)itemId groupId:(NSString * _Nonnull)groupId;
- (void)trackAppPushTokenSetWithDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)trackAppPushOptIn;
- (void)trackAppPushOptOut;
- (void)trackAppPushOpenedWithAppPush:(UNNotification * _Nonnull)appPush;
- (void)trackAppPushDeliveredWithAppPush:(UNNotification * _Nonnull)appPush;
- (void)trackExistingLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone SWIFT_DEPRECATED_MSG("", "trackLoggedInEmail:phone:");
- (void)trackExistingLoggedInEmail:(NSString * _Nonnull)email SWIFT_DEPRECATED_MSG("", "trackLoggedInEmail:");
- (void)trackExistingAffiliateLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber SWIFT_DEPRECATED_MSG("", "trackAffiliateLoggedInEmail:phone:accountType:affiliateNumber:");
- (void)trackHashedExistingLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone SWIFT_DEPRECATED_MSG("", "trackHashedLoggedInEmail:phone:");
- (void)trackHashedExistingLoggedInEmail:(NSString * _Nonnull)email SWIFT_DEPRECATED_MSG("", "trackHashedLoggedInEmail:");
- (void)trackHashedExistingAffiliateLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber SWIFT_DEPRECATED_MSG("", "trackHashedAffiliateLoggedInEmail:phone:accountType:affiliateNumber:");
- (void)trackAddToCartWithItemId:(NSString * _Nonnull)itemId;
- (void)trackEmptyCart;
- (void)trackLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method phone:(NSString * _Nonnull)phone SWIFT_DEPRECATED_MSG("", "trackLoggedInEmail:phone:");
- (void)trackLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone;
- (void)trackLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method SWIFT_DEPRECATED_MSG("", "trackLoggedInEmail:");
- (void)trackLoggedInEmail:(NSString * _Nonnull)email;
- (void)trackAffiliateLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber SWIFT_DEPRECATED_MSG("", "trackAffiliateLoggedInEmail:phone:accountType:affiliateNumber:");
- (void)trackAffiliateLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber;
- (void)trackHashedLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method phone:(NSString * _Nonnull)phone SWIFT_DEPRECATED_MSG("", "trackHashedLoggedInEmail:phone:");
- (void)trackHashedLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone;
- (void)trackHashedLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method SWIFT_DEPRECATED_MSG("", "trackHashedLoggedInEmail:");
- (void)trackHashedLoggedInEmail:(NSString * _Nonnull)email;
- (void)trackHashedAffiliateLoggedInEmail:(NSString * _Nonnull)email method:(enum LoginMethod)method phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber SWIFT_DEPRECATED_MSG("", "trackHashedAffiliateLoggedInEmail:phone:accountType:affiliateNumber:");
- (void)trackHashedAffiliateLoggedInEmail:(NSString * _Nonnull)email phone:(NSString * _Nullable)phone accountType:(enum AccountType)accountType affiliateNumber:(NSString * _Nonnull)affiliateNumber;
- (void)trackLoggedOut;
- (void)trackEndVisit;
- (NSString * _Nonnull)getDeviceID SWIFT_WARN_UNUSED_RESULT;
- (void)trackCustomWithEventName:(NSString * _Nonnull)eventName extraData:(NSDictionary<NSString *, NSString *> * _Nonnull)extraData;
- (void)trackSelectSKUWithGroupId:(NSString * _Nonnull)groupId feedId:(NSString * _Nonnull)feedId;
- (void)trackMultiplePurchasesWithOrders:(NSArray<CustomOrder *> * _Nonnull)orders;
- (void)trackTextOptInPhoneNumber:(NSString * _Nonnull)phoneNumber languageCode:(NSString * _Nullable)languageCode;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
